config/routes.rb
ElecPortalApp::Application.routes.draw do
  resources :rss_items
  resources :rss_feeds
  resources :posts
  resources :topics
  resources :forums
  resources :microposts, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions
  resources :relationships, only: [:create, :destroy]

  get "users/new"
  get "portal_home" => "portal_home#index", :as => "portal_home"
  
  controller :portal_home do
	post 'redeempoints' => :redeem_points
	get 'change_settings' => :change_settings
  end
  root to: 'static_pages#home'

  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match '/feed', to: 'portal_home#feed'
  match '/points_whats_this', to: 'portal_home#points_whats_this'
  match '/customise_feed', to: 'portal_home#customise'
  match '/signup',  to: 'users#new'
  match '/home', 	to: 'static_pages#home'
  match '/signin',	to: 'sessions#new'
  match '/signout',	to: 'sessions#destroy'
  match '/logged_in', to: 'sessions#logged_in'
  match '/settings', to: 'portal_home#settings'
  match '/redeempoints', to: 'portal_home#redeempoints'
  match '/portal_home_redeem', to: 'portal_home#redeem_points'
  match '/edit_settings', to: 'portal_home#edit_settings'
  match '/forum', to: 'forums#index'
  match '/blog', to: 'static_pages#blogs_home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  
  

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  attr_accessible :name, :description
  has_many :topics, :dependent => :destroy
  validates_presence_of :name
  validates_presence_of :description
   
  def most_recent_post  
    topic = Topic.first(:order => 'last_post_at DESC', :conditions => ['forum_id = ?', self.id])  
    return topic  
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_filter :admin_required, :except => [:index, :show]  
  def index
    @forums = Forum.all
  end
 
  def show
    @forum = Forum.find(params[:id])
  end
 
  def new
    @forum = Forum.new
  end
 
  def create
    @forum = Forum.new(params[:forum])
    if @forum.save
      redirect_to @forum, :notice => "Successfully created forum."
    else
      render :action => 'new'
    end
  end
 
  def edit
    @forum = Forum.find(params[:id])
  end
 
  def update
    @forum = Forum.find(params[:id])
    if @forum.update_attributes(params[:forum])
      redirect_to @forum, :notice  => "Successfully updated forum."
    else
      render :action => 'edit'
    end
  end
 
  def destroy
    @forum = Forum.find(params[:id])
    @forum.destroy
    redirect_to forums_url, :notice => "Successfully destroyed forum."
  end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%= form_for @forum do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name,style:"width:440px" %>
    <%= f.label :description %><br />
    <%= f.text_area :description ,style:"height:220px;width:440px"%>
  </p>
  <p><%= f.submit "Create Forum",class:"btn"%><%= link_to "Back to List", forums_path ,class:"btn"%></p>
<% end %>

app/views/forums/edit.html.erb
<h1>Edit Forum</h1>

<%= render 'form' %>

<p>
  <%= link_to "Show", @forum %> |
  <%= link_to "View All", forums_path %>
</p>

app/views/forums/index.html.erb
<h1>Forum List</h1>  

<table class="table table-striped">
        <thead>
          <tr>
           <th>Forum</th>  
          <th>Description</th> 
          <th>Last Post</th> 
          <th>Activity</th> 

          </tr>
        </thead>
        <tbody>
            <% for forum in @forums %>  

          <tr>
            <td><%= link_to h(forum.name), forum_path(forum.id) %></td>
            <td><%= wrap(forum.description) %></td>
            <td> 
                <% if forum.most_recent_post%>
                <% if forum.most_recent_post.last_post_at%>
                <%= distance_of_time_in_words_to_now forum.most_recent_post.last_post_at %> ago 
                <% else %>
                  no posts
                <% end %>
                <% else %>
                  no posts
                <% end %>
            </td>
            <td><%= forum.topics.count %> thread(s)</td>
    <% if admin? %>  
          <td>
            <%= link_to "Edit", edit_forum_path(forum), class:"btn"%>
          </td>  
          <td>
            <%= link_to "Delete", forum, :confirm => 'Are you sure?', :method => :delete ,class:"btn btn-danger"%>
          </td>
    <% end %> 
          </tr>
         <% end %>  

        </tbody>
      </table>
<% if admin? %>    
    <button type="button" class="btn btn-default"><%= link_to "New Forum", new_forum_path %></button>
<% end %>
<!-- <table class="table table-striped table-hover">  
  <tr>  
    <th width="70%">Forum</th>  
    <th width="30%">Last Post</th>  
  </tr>  
  <% for forum in @forums %>  
    <tr>  
      <td><h4><%= link_to h(forum.name), forum_path(forum.id) %></h4>  
        <small><%= forum.topics.count %> topics</small><br />  
         <%=h forum.description %>
      </td>  
      <td class="right">
        <% if forum.most_recent_post%>
        <% if forum.most_recent_post.last_post_at%>
        <%= distance_of_time_in_words_to_now forum.most_recent_post.last_post_at %> ago 
        <% else %>
          no posts
        <% end %>
        <% else %>
          no posts
        <% end %>
      </td>  
	  <% if current_user %>  
		<td><%if current_user.admin%><%= link_to "Edit", edit_forum_path(forum) %><%end%></td>  
		<td><%if current_user.admin%><%= link_to "Destroy", forum, :confirm => 'Are you sure?', :method => :delete %><%end%></td>
	  <% end %>	
    </tr>  
  <% end %>  
</table>  
 -->

app/views/forums/new.html.erb
<h1>New Forum</h1>

<%= render 'form' %>

app/views/forums/show.html.erb
<h1><%= @forum.name  %></h1>
  
<table class="table table-striped table-hover"> 
  <tr>  
    <th width="50%">Thread</th>  
    <th width="10%">Views</th>
    <th width="10%">Replies</th>  
    <th width="30%">Last Post</th>  
  </tr>  
  <% for topic in @forum.topics %>  
    <tr>  
      <td align ="center"><%= link_to h(topic.name), topic_path(topic.id) %>  </td>
      <td align="center"><%= topic.impressionist_count(:filter=>:session_hash) %></td>
      <td align ="center"><%= topic.posts.size%></td>  
      <td align ="center">
	    <% if topic.last_post_at%><%= distance_of_time_in_words_to_now topic.last_post_at %> ago by <%= link_to topic.most_recent_post_username, "/users/#{topic.last_poster_id}" %><% else %>no posts<% end %></td> 
	<% if admin? %><td><%= link_to "Delete", topic, :confirm => 'Are you sure?', :method => :delete, class:"btn btn-danger" %></td><% end %>	</tr>  
  <% end %>  
</table>  
  
<p><% if current_user %><%= link_to "New Thread", "/topics/new?forum=#{@forum.id}", class:"btn" %><% end %><%= link_to "Forum Homepage", "/forums",class:"btn" %></p>