config/routes.rb
ElecPortalApp::Application.routes.draw do
  resources :rss_items
  resources :rss_feeds
  resources :posts
  resources :topics
  resources :forums
  resources :microposts, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions
  resources :relationships, only: [:create, :destroy]

  get "users/new"
  get "portal_home" => "portal_home#index", :as => "portal_home"
  
  controller :portal_home do
	post 'redeempoints' => :redeem_points
	get 'change_settings' => :change_settings
  end
  root to: 'static_pages#home'

  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match '/feed', to: 'portal_home#feed'
  match '/points_whats_this', to: 'portal_home#points_whats_this'
  match '/customise_feed', to: 'portal_home#customise'
  match '/signup',  to: 'users#new'
  match '/home', 	to: 'static_pages#home'
  match '/signin',	to: 'sessions#new'
  match '/signout',	to: 'sessions#destroy'
  match '/logged_in', to: 'sessions#logged_in'
  match '/settings', to: 'portal_home#settings'
  match '/redeempoints', to: 'portal_home#redeempoints'
  match '/portal_home_redeem', to: 'portal_home#redeem_points'
  match '/edit_settings', to: 'portal_home#edit_settings'
  match '/forum', to: 'forums#index'
  match '/blog', to: 'static_pages#blogs_home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  
  

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  is_impressionable
  attr_accessible :name, :last_poster_id, :last_post_at, :forum_id, :user_id
  validates_presence_of :name
  belongs_to :forum
  belongs_to :user
  has_many :posts, :dependent => :destroy
   
  def most_recent_post_username  
    username = User.first().name
    return username 
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  impressionist :actions=>[:show,:index]
  before_filter :admin_required, :only => :destroy
  def index
    @topics = Topic.all
  end
 
  def show
    @topic = Topic.find(params[:id])
    impressionist(@topic)
  end
 
  def new
    @topic = Topic.new
  end
 
  def create
    @forum = Forum.find(params[:topic][:forum_id])
    @topic = Topic.create(:name => params[:topic][:name], :last_poster_id => current_user.id, :forum_id => @forum.id, :user_id => current_user.id)
     
    if @topic.save
        redirect_to "/forums/#{@topic.forum_id}"
    else
      render :action => 'new'
    end
end
 
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to "/forums/#{@topic.forum_id}"
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>  
  <%= f.error_messages %>  
  <% if params[:forum] %><input type="hidden" id="topic_forum_id" name="topic[forum_id]" value="<%= params[:forum] %>" /><% end %>  
  <p>  
    <%= f.label :name %><br />  
    <%= f.text_field :name %>  
  </p>  
  <p><%= f.submit "Create Thread",class:"btn"%><%= link_to "Back to List", topics_path,class:"btn" %></p>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Topics</h1>

<table class="table table-striped table-hover">
  <tr>
    <th>Name</th>
    <th>Views</th>
    <th>Last Poster</th>
    <th>Last Post At</th>
  </tr>
  <% for topic in @topics %>
    <tr>
      <td><%= topic.name %></td>
      <td><%= topic.impressionist_count %></td>
	  <% if topic.last_poster_id %>  
		  <td><%= link_to topic.most_recent_post_username, "/users/#{topic.last_poster_id}" %>  
		  <% else %>no posts<% end %> </td>
      <td><%= topic.last_post_at %></td>
    </tr>
  <% end %>
</table>

app/views/topics/new.html.erb
<h1>New Thread</h1>

<%= render 'form' %>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>
<table class="table table-striped table-hover">
  <tr>
    <th style:"width:25%;">Poster</th>
    <th>Content</th>
  </tr>
	<% for post in @topic.posts %> 
	<tr>
		<td><%= link_to User.find(post.user.id).name, user_url(post.user) %></td>
		<td><%= wrap(post.content) %></td>
		<% if admin? %><td><%= link_to "Delete", post, :confirm => 'Are you sure?', :method => :delete, class:"btn btn-danger" %></td><% end %>	</tr>  
	</tr>
  <% end %>
</table>
 

<p>  
  <% if  current_user %><%= link_to "Reply", "#{new_post_path}?topic=#{@topic.id}" , class:"btn" %> <% end %>  
  <% if current_user.name == "admin" %><%= link_to "Destroy Topic", @topic, :confirm => 'Are you sure?', :method => :delete,  class:"btn"  %> <% end %>  
  <%= link_to "View All Threads", forum_path(@topic.forum_id), class:"btn"  %>  
</p>