config/routes.rb
ElecPortalApp::Application.routes.draw do
  resources :rss_items
  resources :rss_feeds
  resources :posts
  resources :topics
  resources :forums
  resources :microposts, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions
  resources :relationships, only: [:create, :destroy]

  get "users/new"
  get "portal_home" => "portal_home#index", :as => "portal_home"
  
  controller :portal_home do
	post 'redeempoints' => :redeem_points
	get 'change_settings' => :change_settings
  end
  root to: 'static_pages#home'

  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match '/feed', to: 'portal_home#feed'
  match '/points_whats_this', to: 'portal_home#points_whats_this'
  match '/customise_feed', to: 'portal_home#customise'
  match '/signup',  to: 'users#new'
  match '/home', 	to: 'static_pages#home'
  match '/signin',	to: 'sessions#new'
  match '/signout',	to: 'sessions#destroy'
  match '/logged_in', to: 'sessions#logged_in'
  match '/settings', to: 'portal_home#settings'
  match '/redeempoints', to: 'portal_home#redeempoints'
  match '/portal_home_redeem', to: 'portal_home#redeem_points'
  match '/edit_settings', to: 'portal_home#edit_settings'
  match '/forum', to: 'forums#index'
  match '/blog', to: 'static_pages#blogs_home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  
  

end

app/controllers/portal_home_controller.rb
require 'feed-normalizer'
require 'open-uri'
require 'nokogiri'
require 'prawn'
#require 'barby'
#require 'barby/barcode/code_128'
#require 'barby/outputter/png_outputter'
require 'FileUtils'
class PortalHomeController < ApplicationController
	include ActionView::Helpers::TextHelper

	def index
	  @index = true
	end
	
  def feed
  
	@show_feed = true
	if current_user
		feed_items = current_user.rss_feed.rss_items
		@feeds = []
		@max_items = current_user.rss_feed.max_items
		
		for feed_item in feed_items
			if feed_item.url == "Enter feed url here"
			else
				parsed_feed = FeedNormalizer::FeedNormalizer.parse open(feed_item.url.strip)
				if parsed_feed.nil?
				else
					@feeds.push(parsed_feed)
				end
			end
		end	

		@stories = @feeds.size * @max_items
		
		if @feeds.size == 0
			@no_feeds = true
		end
		
		@points = current_user.points
	else
		redirect_to login_url
	end
	render "index"
   end
  
  def customise 
   @rss_feed = current_user.rss_feed
   @customise = true
   @rss_feed_item_1 = @rss_feed.rss_items.first
   @rss_feed_item_2 = @rss_feed.rss_items.second
   @rss_feed_item_3 = @rss_feed.rss_items.third
   render "index"
  
  
  end
  
  
  def points_whats_this
	@points_whats_this = true
	render "index"
  end
  
  def settings
	@show_settings = true
	@user = current_user
	render "index"
	#@user.update_attributes(params[:user])	
  end
  
  def edit_settings
	@edit_settings = true
	@user = current_user
	render "index"
  end
  
  
  def redeempoints
	@redeempoints = true
	render "index"
  end
  
  def redeem_points
    @points_to_redeem = params[:points_redeemed]
	
	if current_user.points < @points_to_redeem.to_i
		#error, not enough points
		flash.now[:alert] = "You don't have enough points!"
		@redeempoints = true
		render "index"
	else
		@points_string = pluralize(@points_to_redeem, "point")
		
		#generate barcode
		#barcode = Barby::Code128B.new('barcode')
		#File.open('/sample_app/assets/images/barcode.png', 'w'){|f|
		#  f.write Barby::PngOutputter.new(barcode).to_png(:height => 20, :margin => 5)
		#}	
		
		#generate pdf - add some more things to it!	
		Prawn::Document.generate("#{Rails.root}/app/assets/redeempoints.pdf") do |pdf|
			pdf.encrypt_document
			pdf.image "#{Rails.root}/app/assets/images/header.png", :height => 80
			pdf.move_down 10
			pdf.span(350, :position => :left) do
			 pdf.text "Coupon for #{@points_string}, redeemable at any USYD Camperdown campus store"
			 pdf.text "*Please note that this is for demonstration purposes only and is not a real thing!"
			end
		end


		#send email
		PointsMailer.points_email(current_user).deliver
		
		#delete pdf
		#File.delete("#{Rails.root}/app/assets/redeempoints.pdf")
		
		#deduct points
		old_points = current_user.points
		current_user.update_attributes(:points => old_points - @points_to_redeem.to_i)	
		
		#render next view
		respond_to do |format|
			format.html { redirect_to portal_home_path, notice: 'A coupon has been sent to your email address.' }
		end
	end
	
  end
  
  def forum
	redirect_to forums_url
  end
  
  def blogs
  end

end

app/helpers/portal_home_helper.rb
module PortalHomeHelper
end

app/views/portal_home/_customisefeed.html.erb
<h4>Customise your feed</h4>
<%= form_for(@rss_feed) do |f| %>
  <% if @rss_feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rss_feed.errors.count, "error") %> prohibited this customisation from being saved:</h2>

      <ul>
      <% @rss_feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="form-inline">
    Set maximum stories per feed: <%= f.number_field :max_items , style: "width:50px;" %>
  
    <%= f.submit "Apply", class: "btn"  %>
  </div>  
  
<% end %>

<h5>Subscribe to up to three feeds - please ensure each URL begins with http:// (hint: RSS feeds typically end in .xml or .rss) </h5>
<%= form_for(@rss_feed_item_1) do |f| %>
  <% if @rss_feed_item_1.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rss_feed_item_1.errors.count, "error") %> prohibited this customisation from being saved:</h2>

      <ul>
      <% @rss_feed_item_1.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
   <div class="form-inline">
                <%= f.url_field :url %>
                <%= f.submit "Subscribe" , class: "btn"  %>
          </div>
<% end %>

<%= form_for(@rss_feed_item_2) do |f| %>
  <% if @rss_feed_item_2.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rss_feed_item_2.errors.count, "error") %> prohibited this customisation from being saved:</h2>

      <ul>
      <% @rss_feed_item_2.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="form-inline">
                <%= f.url_field :url %>
        
                <%= f.submit "Subscribe" , class: "btn"  %>
          </div>
<% end %>

<%= form_for(@rss_feed_item_3) do |f| %>
  <% if @rss_feed_item_3.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rss_feed_item_3.errors.count, "error") %> prohibited this customisation from being saved:</h2>

      <ul>
      <% @rss_feed_item_3.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="form-inline">
                <%= f.url_field :url %>
        
                <%= f.submit "Subscribe" , class: "btn"  %>
          </div>
<% end %>

app/views/portal_home/_feed.html.erb
<p><%= @stories %> stories. Generated: <%= Time.now.strftime("%m/%d/%Y at %I:%M%p") %></p>  
<%= link_to 'Customise feed', customise_feed_path %>		
<% for feed in @feeds %>
<h3><a href="<%= feed.url %>"><%= feed.title %></a></h3>  
<% for entry in feed.entries.first(@max_items) %>
    <h5><a href="<%= entry.url %>"><%= entry.title %></a></h5>
    <p style="color:#444;font-size:90%"><%= ActionView::Base.full_sanitizer.sanitize(entry.content).html_safe %></p>
<% end %></br>	
<% end %>


app/views/portal_home/_home.html.erb
<h4>Welcome, <%= current_user.name %>!</h4>
<p>ELECSociety Portal is a web hub for students studying Electrical Engineering at USYD. Since our common room was brutally shut down last year we have had to relocate to the free and open interwebs - feel free to browse, meet other students and earn some points while you're at it. </p>

app/views/portal_home/_points.html.erb
<h4 align="center">You have <%= pluralize(current_user.points, "point") %>!</h4>

<p align="center"><%= link_to 'What is this?', points_whats_this_path ,class:"btn",style:"width:150px"%></p>
<p align="center"><%= link_to 'Redeem points', redeempoints_path,class:"btn",style:"width:150px"%></p>

app/views/portal_home/_points_whats_this.html.erb
<h4>ELECPortal Points System</h4>
<p>The points system is designed to encourage students to use the portal regularly and interact with the student community. 
	Points are earned by logging in and can be redeemed at any campus store before the end of semester.</p>
<p><%= link_to 'Back', portal_home_path, class:"btn" %></p>

<br />

app/views/portal_home/_redeempoints.html.erb
<h4>Redeem points</h4>

<%= form_tag portal_home_redeem_path do %>
	<p>How many points would you like to redeem? <%= number_field_tag :points_redeemed, nil, min: 1 %></p>
	<p><%= submit_tag "Submit",class: "btn btn-large btn-primary"%></p><p><%= link_to 'Cancel', portal_home_path %></p>
<% end %>

<br />

app/views/portal_home/_settingsformedit.html.erb
<h4>Settings</h4>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </div>  
  <div class="field">
    <%= f.label :signature %><br />
    <%= f.text_area :signature, rows: 6 %>
  </div>  
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>
<%= link_to 'Cancel', settings_path %>

app/views/portal_home/_settingsformshow.html.erb
<h4>Settings</h4>
<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Avatar url:</b>
  <%= @user.avatar.url %>
</p>

<p>
  <b>Signature:</b>
  <%= @user.signature %>
</p>

<%= link_to 'Edit', edit_settings_path %> |
<%= link_to 'Back', portal_home_path %>

app/views/portal_home/index.html.erb
<div class="row">
    <div class="span6">
    	<% if @index %>
			<%= render 'home' %>
		<% elsif @show_feed %>
			<% if @no_feeds %>
				<h4 >No subscribed feeds!</h4>
				<%= link_to 'Add some feeds...', customise_feed_path %>				
			<% else %>
				<%= render 'feed' %>
			<% end %>		
		<% elsif @customise %>
			<%= render 'customisefeed' %>
		<% elsif @show_settings %>
			<%= render 'settingsformshow' %>	
		<% elsif @edit_settings %>
			<%= render 'settingsformedit' %>		
		<% elsif @points_whats_this %>
			<%= render 'points_whats_this' %>	
		<% elsif @redeempoints %>
			<%= render 'redeempoints' %>			
		<% end %>
	</div>
    <div class="span3">
     <%= render 'points' %>     
    </div>
  </div>
<!-- <table width="100%">
  <tr width-"100%">
	<td width="25%" valign="top">
			<p><%= link_to 'Forum', forums_path %></p>
			<p><%= link_to 'Blogs', blog_path %></p>
	</td>
	<td width="50%" valign="top">
	<% if @index %>
		<%= render 'home' %>
	<% elsif @show_feed %>
		<% if @no_feeds %>
			<h3>No subscribed feeds!</h3>
			<%= link_to 'Add some feeds...', customise_feed_path %>				
		<% else %>
			<%= render 'feed' %>
		<% end %>		
	<% elsif @customise %>
		<%= render 'customisefeed' %>
	<% elsif @show_settings %>
		<%= render 'settingsformshow' %>	
	<% elsif @edit_settings %>
		<%= render 'settingsformedit' %>		
	<% elsif @points_whats_this %>
		<%= render 'points_whats_this' %>	
	<% elsif @redeempoints %>
		<%= render 'redeempoints' %>			
	<% end %>
	</td>
	<td  width="25%" valign="top">
		<table border="3">
			<tr><td><%= render 'points' %></td></tr>
		</table>
	</td>
  </tr>
</table>

<br /> -->

app/views/portal_home/redeem_points.html.erb
<h1>Redeem points</h1>

<table width="100%">
  <tr width-"100%">
	<td width="25%" valign="top">
			<p>Forum</p>
			<p>Blogs</p>
			<p><%= link_to 'Settings', settings_path %></p>
	</td>
	<td width="75%">
		<% form_tag do %>
			How many points would you like to redeem? <%= number_field_tag :points_redeemed %>
		<%= submit_tag "Submit" %>
		<% end %>
	</td>
  </tr>
</table>

<br />

app/views/portal_home/settings.html.erb
<h1>Settings</h1>

<table width="100%">
  <tr width-"100%">
	<td width="25%" valign="top">
			<p>Forum</p>
			<p>Blogs</p>
			<p><%= link_to 'Settings', settings_path %></p>
	</td>
	<td width="75%">
		<%= render 'settingsform' %>
	</td>
  </tr>
</table>

<br />